name: Build LoopWorkspace

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby (required for some tools)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies
        run: |
          gem install cocoapods
          pod install --repo-update

      - name: Build LoopWorkspace
        run: |
          xcodebuild -workspace LoopWorkspace.xcworkspace -scheme Loop -configuration Release build
